### PR TITLE
docs(inbound): added doc references to inbound templates

### PR DESCRIPTION
**Pull request by igpetrov**
docs(inbound): added doc references to inbound templates

Refers:

- https://github.com/camunda/team-connectors/issues/275

### CODE REVIEW

**Comment by igpetrov** [comment]
Hi @bastiankoerber,

After merging [inbound connector docs](https://docs.camunda.io/docs/components/connectors/out-of-the-box-connectors/available-connectors-overview/), this PR adds doc references to the element templates.

Please see screenshots below and let me know if wording needs to be changed.

## HTTP Webhook

Screenshot 2023-01-18 at 02 59 17

Screenshot 2023-01-18 at 02 59 30

## GitHub Webhook

Screenshot 2023-01-18 at 03 26 31

Screenshot 2023-01-18 at 03 26 40

**Comment by bastiankoerber** [comment]
> Please see screenshots below and let me know if wording needs to be changed.
Do you mean the description and the embedded links to the documentation??

**Comment by igpetrov** [comment]
@bastiankoerber,

yes, I mean, description of the fields has changed this time, however, since it's the last task I have related to templates, it is worth to have a last final look.

**Review by bastiankoerber — APPROVED** [review]
looks good to me. Thank you @igpetrov

**Pull request merged**
