### PR TITLE
fix(deps): Use recommended docker base images.

### PR DESCRIPTION
**Pull request by sbuettner**
## Related issues

closes camunda/team-connectors/issues/430

### CODE REVIEW

**Review by igpetrov — APPROVED** [review]
Should we also make this explicit at the [release action](https://github.com/camunda/connectors-bundle/blob/main/.github/workflows/RELEASE.yaml)?

**Comment by sbuettner** [comment]
@igpetrov What do you mean by `explicit` in this context? And where exactly?

**Comment by igpetrov** [comment]
> @igpetrov What do you mean by `explicit` in this context? And where exactly?

Sorry, I meant tags [here](https://github.com/camunda/connectors-bundle/blob/main/.github/workflows/RELEASE.yaml#L146).

We currently have `<image>` and `<image>-focal`. Maybe we should have `<image>-jammy` and `<image>-focal`, and `<image>` leading to `<image>-jammy`. Or do you think, it's too much?

**Comment by sbuettner** [comment]
Good question. Lets discuss in architecture session and leave the concept as is for now.

**Pull request merged**
