### PR TITLE
feat: add Connector templates download script

### LINKED ISSUE #11: Download script for element-templates of all connectors in the latest version
__Is your feature request related to a problem? Please describe.__

As a Desktop Modeler user I want a convenient way to download the element-templates for all connectors in the latest version.
It is cumbersome to navigate to the currently 7 download locations and download the element-templates one by one, then place them into the model-elements folder

__Describe the solution you'd like__

the connector bundles repository could host scripts so all element templates can be added by running it.
(Ultimately the modeler should offer a built-in installation feature)

__Describe alternatives you've considered__

Created own script:
`wget -O - https://raw.githubusercontent.com/rob2universe/model-element-templates/main/download.sh | bash`

### PR DESCRIPTION
**Pull request by tmetzke**
## Description

Provides a script that downloads all latest element templates matching the versions of the runtimes in the Docker image.

## Related issues

closes #11

### CODE REVIEW

**Comment by menski** [comment]
Hey thanks for the script, but to be honest I'm not 100% sure if this is a good solution. What is our goal we want to achieve here? That the modelers don't provide the templates out of the box I assume, to be honest I think the solution should be that they do. So is this just a quick fix for a while? Then I would ask my self is this the place where people expect it, why would I check in this repository? Also who maintains this script, it adds a lot of duplication now where the versions and the list of connectors is maintained. Also as a user, what am I doing with the files? I would have to know where to put them correct?  

> all latest element templates matching the versions of the runtimes in the Docker image

Also this is easily inconsistent if a user uses an already released version of the connectors bundle, maybe an older one, and the script is used from the main branch which might have developed further. What I mean it's likely the script downloads the latest templates but it has no direct connection with docker image I run locally.

Sorry if it was to much of a brain dump, if we say this is the way forward for now I'm okay to merge it. I personally think it shouldn't be a long term solution that we promote to users. Feels like a very band aid like solution to me.

**Comment by tmetzke** [comment]
> Hey thanks for the script, but to be honest I'm not 100% sure if this is a good solution. What is our goal we want to achieve here? That the modelers don't provide the templates out of the box I assume, to be honest I think the solution should be that they do. So is this just a quick fix for a while? Then I would ask my self is this the place where people expect it, why would I check in this repository? Also who maintains this script, it adds a lot of duplication now where the versions and the list of connectors is maintained. Also as a user, what am I doing with the files? I would have to know where to put them correct?
> 
> > all latest element templates matching the versions of the runtimes in the Docker image
> 
> Also this is easily inconsistent if a user uses an already released version of the connectors bundle, maybe an older one, and the script is used from the main branch which might have developed further. What I mean it's likely the script downloads the latest templates but it has no direct connection with docker image I run locally.
> 
> Sorry if it was to much of a brain dump, if we say this is the way forward for now I'm okay to merge it. I personally think it shouldn't be a long term solution that we promote to users. Feels like a very band aid like solution to me.

Thanks for those thoughts, @menski. All valid, I think. Especially the missing connection between the Docker image I might be running and the download script I am using. 👍 

I am also fine with not providing something like this at all here but rather pushing for a convenient solution within our modelers themselves. 

In the end, I think there is a certain need for a convenient method to fetch all templates at once, especially for trial users. Happy for any other ideas here. Or a better place to provide this (without any guarantees but rather as a shortcut people can/have to maintain themselves for now).

**Comment by menski** [comment]
In my mind I have two random ideas:

1. Bundle the element templates in the docker image itself, i.e. while fetching the connector jars also fetch the corresponding element templates. The user could the use a `docker cp` command to extract the templates for the running container, has the disadvantage that the container has to run.
2. Modify the script in a way that is is always usable from the main branch, but instead of having the connectors listed explicitly only contain the version of the connectors bundle, which can also be set when run the script, and the the script fetches the Dockerfile for the given connectors bundle version and extracts connectors and version from the Dockerfile.

For both solution it would be really nice if the jar file contains the element template, but I assume that is not the case right?

**Comment by tmetzke** [comment]
> For both solution it would be really nice if the jar file contains the element template, but I assume that is not the case right?

Correct, not contained in the JARs currently.

**Comment by menski** [comment]
@tmetzke how we want to continue here? Just making progress and merge? Or thinking about different solutions?

**Comment by tmetzke** [comment]
I am not all that certain anymore that this will really help more than it harms in this place here. I still think there is a need for it. But maybe not here. Let's discuss this in the team meeting maybe.

**Comment by menski** [comment]
@tmetzke should we close this in favor of #14

**Comment by tmetzke** [comment]
Closed as superseded by #14

**Pull request closed without merging**
