### PR TITLE
Fix native AWS objects serialization

### PR DESCRIPTION
**Pull request by igpetrov**
## Description

Due to multiple instances of GSON, in a bundled version that contains all the connectors, there is a conflict between the GSON instances. As such, some deserializers seem not to be registered / working as expected.

### CODE REVIEW

**Comment by tmetzke** [comment]
Don't we have other Connectors like Slack that use this mechanism in GSON as well? Are they affected as well?

**Comment by igpetrov** [comment]
> Don't we have other Connectors like Slack that use this mechanism in GSON as well? Are they affected as well?

It is somewhat similar for Slack but it doesn't seem to reproduce. For some reason, in only reproduces for SNS only. I refactored SQS as well since it's the same logic.

But overall, we have a bigger issue that gson instances somehow overlap.

**Comment by tmetzke** [comment]
> But overall, we have a bigger issue that gson instances somehow overlap.

We should try to find out what the real issue here is. It might be an issue with the shading approach or how we configure GSON for SQS and SNS. I can see the following in the [build logs](https://github.com/camunda/connectors-bundle/actions/runs/3658980382/jobs/6184441998) (step `Build Artifacts`):

```
Warning:  connector-sns-0.14.0-SNAPSHOT.jar, connector-sqs-0.14.0-SNAPSHOT.jar define 3 overlapping classes: 
Warning:    - io.camunda.connector.model.AuthenticationRequestData
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier$MessageAttributeValueDeserializer
```
I cannot see anything for the other Connectors, so they might be actually fine.

This is the shading log:
```
[INFO] --- maven-shade-plugin:3.4.1:shade (default) @ connector-runtime-bundle ---
[INFO] Including io.camunda:spring-zeebe-connector-runtime:jar:8.1.9 in the shaded jar.
[INFO] Including io.camunda.connector:connector-runtime-util:jar:0.4.0-SNAPSHOT in the shaded jar.
[INFO] Including io.camunda.connector:connector-core:jar:0.4.0-SNAPSHOT in the shaded jar.
[INFO] Including io.camunda:zeebe-client-java:jar:8.1.5 in the shaded jar.
[INFO] Including io.camunda:zeebe-bpmn-model:jar:8.1.5 in the shaded jar.
[INFO] Including org.camunda.bpm.model:camunda-xml-model:jar:7.17.0 in the shaded jar.
[INFO] Including io.camunda:zeebe-gateway-protocol-impl:jar:8.1.5 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf:jar:1.49.1 in the shaded jar.
[INFO] Including com.google.api.grpc:proto-google-common-protos:jar:2.9.0 in the shaded jar.
[INFO] Including io.grpc:grpc-protobuf-lite:jar:1.49.1 in the shaded jar.
[INFO] Including io.grpc:grpc-stub:jar:1.49.1 in the shaded jar.
[INFO] Including io.grpc:grpc-core:jar:1.49.1 in the shaded jar.
[INFO] Including com.google.android:annotations:jar:4.1.1.4 in the shaded jar.
[INFO] Including org.codehaus.mojo:animal-sniffer-annotations:jar:1.21 in the shaded jar.
[INFO] Including io.perfmark:perfmark-api:jar:0.25.0 in the shaded jar.
[INFO] Including io.grpc:grpc-api:jar:1.49.1 in the shaded jar.
[INFO] Including io.grpc:grpc-context:jar:1.49.1 in the shaded jar.
[INFO] Including io.grpc:grpc-netty:jar:1.49.1 in the shaded jar.
[INFO] Including com.google.protobuf:protobuf-java:jar:3.21.9 in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-classes:jar:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.54.Final in the shaded jar.
[INFO] Including io.netty:netty-handler:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-codec:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-common:jar:4.1.82.Final in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.14.0 in the shaded jar.
[INFO] Including org.camunda.feel:feel-engine:jar:1.15.3 in the shaded jar.
[INFO] Including org.scala-lang:scala-library:jar:2.13.9 in the shaded jar.
[INFO] Including com.lihaoyi:fastparse_2.13:jar:2.3.3 in the shaded jar.
[INFO] Including com.lihaoyi:sourcecode_2.13:jar:0.2.3 in the shaded jar.
[INFO] Including com.lihaoyi:geny_2.13:jar:0.6.10 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-scala_3:jar:2.14.1 in the shaded jar.
[INFO] Including org.scala-lang:scala3-library_3:jar:3.2.0 in the shaded jar.
[INFO] Including com.thoughtworks.paranamer:paranamer:jar:2.8 in the shaded jar.
[INFO] Including io.camunda.connector:connector-validation:jar:0.4.0-SNAPSHOT in the shaded jar.
[INFO] Including jakarta.validation:jakarta.validation-api:jar:2.0.2 in the shaded jar.
[INFO] Including org.hibernate.validator:hibernate-validator:jar:6.2.5.Final in the shaded jar.
[INFO] Including org.jboss.logging:jboss-logging:jar:3.4.1.Final in the shaded jar.
[INFO] Including com.fasterxml:classmate:jar:1.5.1 in the shaded jar.
[INFO] Including io.camunda:spring-zeebe-starter:jar:8.1.9 in the shaded jar.
[INFO] Including org.springframework.boot:spring-boot-starter:jar:2.7.5 in the shaded jar.
[INFO] Including org.springframework.boot:spring-boot:jar:2.7.5 in the shaded jar.
[INFO] Including org.springframework.boot:spring-boot-autoconfigure:jar:2.7.5 in the shaded jar.
[INFO] Including org.springframework.boot:spring-boot-starter-logging:jar:2.7.5 in the shaded jar.
[INFO] Including ch.qos.logback:logback-classic:jar:1.2.11 in the shaded jar.
[INFO] Including ch.qos.logback:logback-core:jar:1.2.11 in the shaded jar.
[INFO] Including com.github.luben:zstd-jni:jar:1.5.2-1 in the shaded jar.
[INFO] Including org.lz4:lz4-java:jar:1.8.0 in the shaded jar.
[INFO] Including org.xerial.snappy:snappy-java:jar:1.1.8.4 in the shaded jar.
[INFO] Including io.camunda.connector:connector-microsoft-teams:jar:0.14.0-SNAPSHOT in the shaded jar.
[INFO] Including com.microsoft.graph:microsoft-graph:jar:5.41.0 in the shaded jar.
[INFO] Including com.microsoft.graph:microsoft-graph-core:jar:2.0.14 in the shaded jar.
[INFO] Including com.azure:azure-identity:jar:1.7.1 in the shaded jar.
[INFO] Including com.azure:azure-core:jar:1.34.0 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.13.4 in the shaded jar.
[INFO] Including org.codehaus.woodstox:stax2-api:jar:4.2.1 in the shaded jar.
[INFO] Including com.fasterxml.woodstox:woodstox-core:jar:6.4.0 in the shaded jar.
[INFO] Including io.projectreactor:reactor-core:jar:3.4.23 in the shaded jar.
[INFO] Including org.reactivestreams:reactive-streams:jar:1.0.4 in the shaded jar.
[INFO] Including com.azure:azure-core-http-netty:jar:1.12.7 in the shaded jar.
[INFO] Including io.netty:netty-handler-proxy:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-socks:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-buffer:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-http:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-http2:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport-native-unix-common:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport-classes-epoll:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.82.Final in the shaded jar.
[INFO] Including io.netty:netty-transport-classes-kqueue:jar:4.1.82.Final in the shaded jar.
[INFO] Including io.projectreactor.netty:reactor-netty-http:jar:1.0.23 in the shaded jar.
[INFO] Including io.netty:netty-resolver-dns:jar:4.1.81.Final in the shaded jar.
[INFO] Including io.netty:netty-codec-dns:jar:4.1.81.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.81.Final in the shaded jar.
[INFO] Including io.netty:netty-resolver-dns-classes-macos:jar:4.1.81.Final in the shaded jar.
[INFO] Including io.projectreactor.netty:reactor-netty-core:jar:1.0.23 in the shaded jar.
[INFO] Including com.microsoft.azure:msal4j:jar:1.13.3 in the shaded jar.
[INFO] Including com.nimbusds:oauth2-oidc-sdk:jar:9.35 in the shaded jar.
[INFO] Including com.github.stephenc.jcip:jcip-annotations:jar:1.0-1 in the shaded jar.
[INFO] Including com.nimbusds:content-type:jar:2.2 in the shaded jar.
[INFO] Including com.nimbusds:lang-tag:jar:1.6 in the shaded jar.
[INFO] Including com.nimbusds:nimbus-jose-jwt:jar:9.22 in the shaded jar.
[INFO] Including net.minidev:json-smart:jar:2.4.8 in the shaded jar.
[INFO] Including net.minidev:accessors-smart:jar:2.4.8 in the shaded jar.
[INFO] Including org.ow2.asm:asm:jar:9.1 in the shaded jar.
[INFO] Including com.microsoft.azure:msal4j-persistence-extension:jar:1.1.0 in the shaded jar.
[INFO] Including net.java.dev.jna:jna:jar:5.5.0 in the shaded jar.
[INFO] Including net.java.dev.jna:jna-platform:jar:5.6.0 in the shaded jar.
[INFO] Excluding javax.annotation:jsr250-api:jar:1.0 from the shaded jar.
Warning:  kafka-clients-3.3.1.jar, scala-library-2.13.9.jar define 1 overlapping resource: 
Warning:    - NOTICE
Warning:  connector-sns-0.14.0-SNAPSHOT.jar, connector-sqs-0.14.0-SNAPSHOT.jar define 3 overlapping classes: 
Warning:    - io.camunda.connector.model.AuthenticationRequestData
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier$MessageAttributeValueDeserializer
Warning:  accessors-smart-2.4.8.jar, nimbus-jose-jwt-9.22.jar define 2 overlapping resources: 
Warning:    - META-INF/maven/net.minidev/accessors-smart/pom.properties
Warning:    - META-INF/maven/net.minidev/accessors-smart/pom.xml
Warning:  commons-logging-1.1.3.jar, spring-jcl-5.3.23.jar define 5 overlapping classes: 
Warning:    - org.apache.commons.logging.Log
Warning:    - org.apache.commons.logging.LogFactory
Warning:    - org.apache.commons.logging.LogFactory$1
Warning:    - org.apache.commons.logging.impl.NoOpLog
Warning:    - org.apache.commons.logging.impl.SimpleLog
Warning:  jna-5.5.0.jar, jna-platform-5.6.0.jar define 2 overlapping resources: 
Warning:    - META-INF/AL2.0
Warning:    - META-INF/LGPL2.1
Warning:  httpclient-4.5.13.jar, httpclient5-5.1.3.jar define 1 overlapping resource: 
Warning:    - mozilla/public-suffix-list.txt
Warning:  netty-tcnative-boringssl-static-2.0.54.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-windows-x86_64.jar define 4 overlapping resources: 
Warning:    - META-INF/license/LICENSE.aix-netbsd.txt
Warning:    - META-INF/license/LICENSE.boringssl.txt
Warning:    - META-INF/license/LICENSE.mvn-wrapper.txt
Warning:    - META-INF/license/LICENSE.tomcat-native.txt
Warning:  camunda-operate-client-java-1.3.5.jar, connector-runtime-bundle-0.14.0-SNAPSHOT.jar, spring-zeebe-connector-runtime-8.1.9.jar define 1 overlapping resource: 
Warning:    - application.properties
Warning:  kafka-clients-3.3.1.jar, scala-library-2.13.9.jar, sendgrid-java-4.9.3.jar define 1 overlapping resource: 
Warning:    - LICENSE
Warning:  json-smart-2.4.8.jar, nimbus-jose-jwt-9.22.jar define 2 overlapping resources: 
Warning:    - META-INF/maven/net.minidev/json-smart/pom.properties
Warning:    - META-INF/maven/net.minidev/json-smart/pom.xml
Warning:  spring-web-5.3.23.jar, tomcat-embed-el-9.0.68.jar, tomcat-embed-websocket-9.0.68.jar define 1 overlapping resource: 
Warning:    - META-INF/web-fragment.xml
Warning:  netty-tcnative-boringssl-static-2.0.54.Final-linux-aarch_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-linux-x86_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-osx-aarch_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-osx-x86_64.jar, netty-tcnative-boringssl-static-2.0.54.Final-windows-x86_64.jar, netty-tcnative-boringssl-static-2.0.54.Final.jar define 2 overlapping resources: 
Warning:    - META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.properties
Warning:    - META-INF/maven/io.netty/netty-tcnative-boringssl-static/pom.xml
Warning:  maven-shade-plugin has detected that some class files are
Warning:  present in two or more JARs. When this happens, only one
Warning:  single version of the class is copied to the uber jar.
Warning:  Usually this is not harmful and you can skip these warnings,
Warning:  otherwise try to manually exclude artifacts based on
Warning:  mvn dependency:tree -Ddetail=true and the above output.
Warning:  See https://maven.apache.org/plugins/maven-shade-plugin/
```

**Comment by igpetrov** [comment]
> `Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier$MessageAttributeValueDeserializer`.

Feeling that it could be it. Deserializer name is (was) the same. In fact, they SNS is a copy-paste of SQS, except there's 1 different import.

It is weird tho, that I cannot reproduce it in SM.

> I cannot see anything for the other Connectors, so they might be actually fine.

Yes, I have one big diagram for all connectors (except MS Teams) and all seem to work fine. It's just SNS who didn't work out.

**Comment by igpetrov** [comment]
I am going to actually rename other classes as well:

```
Warning:    - io.camunda.connector.model.AuthenticationRequestData
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier
Warning:    - io.camunda.connector.suppliers.GsonComponentSupplier$MessageAttributeValueDeserializer
```

**Comment by tmetzke** [comment]
Just wondering: wouldn't it be enough to adjust the overlapping classes (e.g. by introducing a proper package name that resembles the specific Connector)?

**Review by tmetzke — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
