### PR TITLE
Revert "fix(deps): update dependency com.google.cloud:libraries-bom t…

### PR DESCRIPTION
**Pull request by chillleader**
## Description

Revert broken dependency bumps (we can investigate after the patch release)

## Related issues

related to camunda/team-connectors#272

### CODE REVIEW

**Comment by tmetzke** [comment]
Are those really broken? The job that fails is rather flaky as it cannot assign the renovate bot as assignee to the PR which makes sense. We can simply fix the workflow.

**Comment by chillleader** [comment]
Oh ok, I just had an issue with the local build and I thought that it's the same in GitHub. Must be my local issue then, sry.

**Comment by tmetzke** [comment]
If you need help figuring out what's wrong, let me know 👍

**Comment by tmetzke** [comment]
@chillleader, can you create a follow-up to prevent renovate from auto-merging updates? For serious projects, I think that's not the best idea. We should decide ourselves when to update dependencies.

**Comment by chillleader** [comment]
Created https://github.com/camunda/team-connectors/issues/278 in team-connectors, since we probably want to check other repositories as well

**Pull request closed without merging**
